[project]
name = "fitbit-garmin-converter"
version = "0.1.0"
description = "Convert Fitbit exported data to Garmin Connect format"

requires-python = "~=3.11.0"
dependencies = [
    "typer",
    "pandas",
    "uv",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "syrupy",
]
